// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTx0RI98VIeDyA2vXhBD1S_owZCfBUgfo',
    appId: '1:938358879483:web:01e9d2c9e3dbe030b0ac5e',
    messagingSenderId: '938358879483',
    projectId: 'essentials-14dde',
    authDomain: 'essentials-14dde.firebaseapp.com',
    storageBucket: 'essentials-14dde.appspot.com',
    measurementId: 'G-3YEVLS71WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtUF8A5nf_gtO_GAahunpEpPOd2J76An4',
    appId: '1:938358879483:android:5c0705f84a4074e6b0ac5e',
    messagingSenderId: '938358879483',
    projectId: 'essentials-14dde',
    storageBucket: 'essentials-14dde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFyYtT9-NqDmalpr8X5aJni2oPTm2nslE',
    appId: '1:938358879483:ios:d81144aea11b3723b0ac5e',
    messagingSenderId: '938358879483',
    projectId: 'essentials-14dde',
    storageBucket: 'essentials-14dde.appspot.com',
    iosBundleId: 'com.example.essentials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFyYtT9-NqDmalpr8X5aJni2oPTm2nslE',
    appId: '1:938358879483:ios:d81144aea11b3723b0ac5e',
    messagingSenderId: '938358879483',
    projectId: 'essentials-14dde',
    storageBucket: 'essentials-14dde.appspot.com',
    iosBundleId: 'com.example.essentials',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTx0RI98VIeDyA2vXhBD1S_owZCfBUgfo',
    appId: '1:938358879483:web:14e8f0305750a91bb0ac5e',
    messagingSenderId: '938358879483',
    projectId: 'essentials-14dde',
    authDomain: 'essentials-14dde.firebaseapp.com',
    storageBucket: 'essentials-14dde.appspot.com',
    measurementId: 'G-SDQ0P15XN0',
  );
}
